include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-raw-types: true
    strict-casts: true
  errors:
    missing_required_param: error
    missing_return: error
    dead_code: warning
    invalid_use_of_visible_for_testing_member: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"

linter:
  rules:
    # Importación y orden
    always_use_package_imports: true
    directives_ordering: true

    # Estilo y consistencia
    prefer_single_quotes: true
    eol_at_end_of_file: true
    require_trailing_commas: true
    sort_constructors_first: true

    # Const y finales
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    unnecessary_late: true

    # Flutter/Dart moderno
    use_super_parameters: true
    depend_on_referenced_packages: true

    # Ruido común
    avoid_print: true